実装/西村/確認済み/itemmas/urls.py
"""itemmas.urls.py

* 商品マスタの画面をルーティングするモジュール

Todo:

    これ見てgitのappsのurls全部変更お願いします
    このアプリで使用するhtmlのpathを全て追加
    pathのurlpatternsを矢印の下のもので統一してください!
    * nameはhtml組と要相談

"""
from django.urls import path
from . import views

app_name = 'itemmas'
urlpatterns = [
    path('S03-01/',views.S0301View.as_view(),name = "S03-01"), #商品情報一覧
    path('S03-02/',views.S0302View.as_view(),name = "S03-02"), #商品情報新規登録
    path('S03-03/<pk>/',views.S0303View.itemdetail,name = "S03-03"), #商品情報詳細
    path('S03-04/<pk>/',views.S0304View.as_view(),name = "S03-04"), #商品情報編集
    path('S03-05/',views.S0305View.as_view(),name = "S03-05"), #商品情報新規登録
]

実装/西村/確認済み/itemmas/models.py
"""itemmas.models.py

* DBの商品情報モデルにアクセスするためのモジュール

Todo:
    新満の確認

    *マイグレーションができるか確認
    *CSVファイルからデータをコピーできる
    *新満の最終確認

"""
from django.db import models
from storemas.models import StoreInfo


class ItemInfo(models.Model):

    """ ItemInfo

    商品情報モデル

    """
    catchoice = (
        (0,'ノートPC'),
        (1,'デスクトップ'),
        (2,'モニター'),
        (3,'メモリ'),
        (4,'HDD'),
        (5,'SDD'),
        (6,'Office'),
        (7,'その他')
    )
    ischoice = (
        (0,'販売中'),
        (1,'販売済み'),
        (2,'修理中'),
        (3,'取置'),
    )

    id = models.CharField(verbose_name='商品コード',db_column='item_code',max_length=9,primary_key=True)
    model_number = models.CharField(verbose_name='型番', max_length=60)
    category = models.SmallIntegerField(verbose_name='カテゴリ', choices=catchoice)
    manufacturer_name = models.CharField(verbose_name='メーカー名', max_length=30)
    item_status = models.SmallIntegerField(verbose_name='商品状態', choices=ischoice)
    purchase_price = models.IntegerField(verbose_name='仕入価格')
    item_image = models.ImageField(verbose_name='商品画像',blank=True,null=True)
    remarks = models.TextField(verbose_name='備考',blank=True,null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='最終更新日時', auto_now=True)
    store_id = models.ForeignKey(StoreInfo,verbose_name='店舗名', db_column='store_id', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = '商品情報モデル'
    
    def __str__(self):
        return self.id

class ItemSpecification(models.Model):

    """ ItemSpecification

        商品スペックモデル

    """
    id = models.AutoField(verbose_name='スペックID',db_column='spec_id',primary_key=True,editable=False)
    model_number = models.CharField(verbose_name='型番', max_length=60)
    cpu = models.CharField(verbose_name='CPU',default='無し',blank=True,max_length=60)
    hdd = models.FloatField(verbose_name='HDD',default='0',blank=True)
    ssd = models.SmallIntegerField(verbose_name='SSD',default='0',blank=True)
    monitor_size = models.FloatField(verbose_name='モニタサイズ',default='0',blank=True)
    monitor_vertical = models.SmallIntegerField(verbose_name='モニタ解像度(縦)',default='0',blank=True)
    monitor_horizon = models.SmallIntegerField(verbose_name='モニタ解像度(横)',default='0',blank=True)
    camera = models.BooleanField(verbose_name='カメラ',default=0)
    wifi = models.BooleanField(verbose_name='Wi-Fi',default=0)
    optical_drive = models.BooleanField(verbose_name='光学ドライブ',default=0)
    graphic = models.CharField(verbose_name='グラフィック',default='無し',blank=True,max_length=40)
    os = models.CharField(verbose_name='OS',default='無し',blank=True,max_length=40)

    class Meta:
        verbose_name_plural = '商品スペックモデル'

実装/西村/確認済み/itemmas/templates/mas_item_detail.html
<!-- S03-03 商品情報詳細

    ToDo
        画面の制作お願いします
        画面の確認
        *views.py、forms.pyの埋め込みタグを記述
        *画面の確認
        *画面のスタイル最終調整
        *最終確認(新満)

-->

{% extends 'base.html' %}

{% block title %}SIMS | 商品情報詳細{% endblock %}

{% block main_contents %}

<main>
    <div class="container-fluid px-4">
        <h1 class="mt-4">商品管理</h1>

        <div class="row">
            <div class="card mb-4">

                <div class="card-header">
                    <i class="fas fa-table me-1"></i>
                    商品情報詳細
                </div>

                <div class="itemmas-table item-table">
                    
                    <h2>{{ object.model_number }}</h2>
                        <table>
                            <thead class="tablecolumn">
                                <tr>
                                    <th>商品コード</th>
                                    <td>{{ object.id }}</td>
                                    <th>型番</th>
                                    <td>{{ object.model_number }}</td>
                                </tr>
                                <tr>
                                    <th>カテゴリ</th>
                                    <td>{{ object.get_category_display }}</td>
                                    <th>仕入価格</th>
                                    <td>{{ object.purchase_price }}</td>
                                </tr>
                                <tr>
                                    <th>メーカー名</th>
                                    <td>{{ object.manufacturer_name }}</td>
                                    <th>備考</th>
                                    <td>{{ object.remarks }}</td>
                                </tr>
                                <tr>
                                    <th>商品画像</th>
                                    <td>
                                    {% if object.item_image %}
                                        <img src="{{ object.item_image.url }}" width="200" height="200">
                                    {% endif %}
                                    </td>
                                    <th>店舗名(在庫場所)</th>
                                    <td>{{ object.store_id }}</td>
                                </tr>
                            </thead>
                        </table>
                    </div>

                    <div class="itemmas-table spec-table">
                        <table>
                            <thead class="tablecolumn">
                                <tr>
                                    <th>モニタサイズ</th>
                                    <td>{{object_detail.monitor_size}}</td>
                                    <th>OS</th>
                                    <td>{{object_detail.os}}</td>
                                </tr>
                                <tr>
                                    <th>CPU</th>
                                    <td>{{object_detail.cpu}}</td>
                                    <th>モニタ解像度(縦)</th>
                                    <td>{{object_detail.monitor_vertical}}</td>
                                </tr>
                                <tr>
                                    <th>HDD</th>
                                    <td>{{object_detail.hdd}}</td>
                                    <th>モニタ解像度(横)</th>
                                    <td>{{object_detail.monitor_horizon}}</td>
                                </tr>
                                <tr>
                                    <th>SSD</th>
                                    <td>{{object_detail.ssd}}</td>
                                    <th>カメラ</th>
                                    <td>{{object_detail.camera}}</td>
                                </tr>
                                <tr>
                                    <th>光学ドライブ</th>
                                    <td>{{object_detail.optical_drive}}</td>
                                    <th>Wi-Fi</th>
                                    <td>{{object_detail.wifi}}</td>
                                </tr>
                                <tr>
                                    <th>グラフィック</th>
                                    <td>{{object_detail.graphic}}</td>
                                    <th>型番</th>
                                    <td>{{object_detail.model_number}}</td>
                                </tr>
                            </thead>
                        </table>
                    <form method="POST">
                        {% csrf_token %}
                        <div class="center-button">
                            <a class="btn btn-primary" href="{% url 'itemmas:S03-04' object.pk %}">編集</a>
                            <button class="btn btn-primary" type="submit">削除</button>
                        </div>
                    </form>


                </div>
            </div>
        </div>
    </div>
</main>


{% endblock %}

実装/西村/確認済み/itemmas/templates/mas_item_edit.html
<!-- S03-04 商品情報編集

    ToDo
        画面の制作お願いします
        画面の確認
        *views.py、forms.pyの埋め込みタグを記述
        *画面の確認
        *画面のスタイル最終調整
        *最終確認(新満)

-->

{% extends 'base.html' %}

{% block title %}SIMS | 商品情報編集{% endblock %}

{% block main_contents %}
<main>
    <div class="container-fluid px-4">
        <h1 class="mt-4">商品管理</h1>

        <div class="row">
            <div class="card mb-4">

                <div class="card-header">
                    <i class="fas fa-table me-1"></i>
                    商品情報編集
                </div>

                <div class="itemmas-table item-table">
                    <div class="item-image">
                        <img border="1" class="image-content" src="../images/img001.gif" width="128px" height="128px" alt="イラスト1">

                    </div>
                    <input type="file">
                    
                    <h2>型番</h2>
                        <table>
                            <thead class="tablecolumn">
                        
                                <tr>
                                    <th>商品コード</th>
                                    <td><input type="text" id="uitem-code" name="item-code" placeholder="商品コード"></td>
                                    <th>型番</th>
                                    <td><input type="text" id="" name="" placeholder="型番"></td>
                                </tr>
                                <tr>
                                    <th>カテゴリ</th>
                                    <td>
                                        <select name="category" class="categorylist">
                                            <option value="note">ノートPC</option>
                                            <option value="cpu">CPU</option>
                                            <option value="gpu">GPU</option>
                                            <option value="pc">PC</option>
                                            <option value="" selected>-</option>
                                    </td>
                                    <th>仕入価格</th>
                                    <td><input type="text" id="" name="" placeholder="仕入価格"></td>
                                </tr>
                                <tr>
                                    <th>在庫場所</th>
                                    <td>
                                        <select name="balance_score" class="scorelist">
                                            <option value="A">店舗A</option>
                                            <option value="B">店舗B</option>
                                            <option value="C">店舗C</option>
                                            <option value="" selected>-</option>
                                    </td>
                                    <th>備考</th>
                                    <td><input type="text" id="" name="" placeholder="備考"></td>
                                </tr>
                            </thead>
                        </table>
                    </div>

                    <div class="itemmas-table spec-table">
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                        <table class="table">
                            {{ form.as_table }}
                            <!-- <thead class="tablecolumn">
                                <tr>
                                    <th>メーカー</th>
                                    <td><input type="text" id="" name="" placeholder="メーカー"></td>
                                    <th>モニタサイズ</th>
                                    <td><input type="text" id="" name="" placeholder="モニタサイズ"></td>
                                </tr>
                                <tr>
                                    <th>CPU</th>
                                    <td><input type="text" id="" name="" placeholder="CPU"></td>
                                    <th>モニタ解像度(縦)</th>
                                    <td><input type="text" id="" name="" placeholder="解像度(縦)"></td>
                                </tr>
                                <tr>
                                    <th>HDD</th>
                                    <td><input type="text" id="" name="" placeholder="HDD"></td>
                                    <th>モニタ解像度(横)</th>
                                    <td><input type="text" id="" name="" placeholder="解像度(横)"></td>
                                </tr>
                                <tr>
                                    <th>SSD</th>
                                    <td><input type="text" id="" name="" placeholder="SSD"></td>
                                    <th>カメラ</th>
                                    <td><input type="text" id="" name="" placeholder="カメラ"></td>
                                </tr>
                                <tr>
                                    <th>OS</th>
                                    <td><input type="text" id="" name="" placeholder="OS"></td>
                                    <th>光学ドライブ</th>
                                    <td><input type="text" id="" name="" placeholder="光学ドライブ"></td>
                                </tr>
                                <tr>
                                    <th>Wi-Fi</th>
                                    <td><input type="text" id="" name="" placeholder="Wi-Fi"></td>
                                    <th>グラフィック</th>
                                    <td><input type="text" id="" name="" placeholder="グラフィック"></td>
                                </tr>
                            </thead> -->
                        </table>
                        <div class="center-button">
                            <button class="btn btn-primary" type="submit">更新</button>
                        </div>
                    </form>


                </div>
            </div>
        </div>
    </div>
</main>

{% endblock %}

実装/西村/確認済み/itemmas/templates/mas_item_list.html
<!-- S03-01 商品情報一覧

    ToDo
        *画面の制作お願いします
        *画面の確認
        *views.py、forms.pyの埋め込みタグを記述
        *画面の確認
        *画面のスタイル最終調整
        *最終確認(新満)
        
-->

{% extends 'base.html' %}

{% block title %}SIMS | 商品情報一覧{% endblock %}

{% block main_contents %}
<main>
    <div class="container-fluid px-4">
        <h1 class="mt-4">商品管理</h1>
        <div class="row">
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table me-1"></i>
                    商品情報一覧
                </div>
                <div class="card-body">
                    <a class="btn btn-touroku" href="#">検索</a>
                    <a class="btn btn-touroku" href="{% url 'itemmas:S03-02' %}">新規登録</a>
                    <button class="btn btn-primary" type="submit"><a href="{% url 'itemmas:S03-05' %}">詳細登録</a></button>
                    <div class="content">
                        <div class="item">
                            <table class="listtable">
                                <thead class="tablecolumn">
                                    <tr>
                                        <!-- <th>id</th> -->
                                        <th>商品コード</th>
                                        <th>型番</th>
                                        <th>カテゴリ</th>
                                        <th>在庫場所</th>
                                        <th>仕入価格</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <!-- ItemListモデルの一覧を表示 -->
                                {% for item in ItemList %}
                                
                                <tr>
                                    <th><a href="{% url 'itemmas:S03-03' item.pk %}">{{ item.id }}</a></th> <!--商品コード-->
                                    <!-- <td>{{ item.item_code }</td> 型番 -->
                                    <td>{{ item.model_number }}</td> <!--型番-->
                                    <td>{{ item.get_category_display }}</td> <!--カテゴリ-->
                                    <td>{{ item.store_id.store_name }}</td> <!--在庫場所-->
                                    <td>{{ item.purchase_price }}¥</td> <!--仕入価格-->
                                </tr>   
                                {% empty %}
                                <p>空です</p>
                                {% endfor %}

                                    <!-- ページネーション処理 -->
                                    {% if is_paginated %}
                                    <ul class="pagination">
                                        <!-- 前ページへのリンク -->
                                        {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                                <span aria-hidden="true">&laquo;</span>
                                            </a>
                                        </li>
                                        {% endif %}

                                        <!-- ページ数表示 -->
                                        {% for page_num in page_obj.paginator.page_range %}
                                        {% if page_obj.number == page_num %}
                                        <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
                                        {% else %}
                                        <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
                                        {% endif %}
                                        {% endfor %}

                                        <!-- 次ページへのリンク -->
                                        {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                                <span aria-hidden="true">&raquo;</span>
                                            </a>
                                        </li>
                                        {% endif %}
                                    </ul>
                                    {% endif %}
                                </tbody>
                            </table>
                        </div>
                        <!-- <div class="item">
                            <aside>
                                <div class="summary">
                                    <div class="summary-total-items"><span class="total-items"></span>移動指示入力</div>
                                    <table class="deliverytable">
                                        <thead>
                                            <tr>
                                                <th>商品コード</th>
                                                <th>型番</th>
                                                <th>在庫場所</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>123456789</td>
                                                <td>FMVU75EUV1</td>
                                                <td>店舗A</td>
                                                <td style="border:none;">
                                                    <a class="btn btn-small" href="#">削除</a>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    <div class="summary-delivery">
                                        <select name="delivery-collection" class="summary-delivery-selection">
                                            <option hidden>移動先選択</option>
                                            <option value="">店舗A</option>
                                            <option value="">店舗B</option>
                                        </select>
                                    </div>
                                    <a class="btn btn-touroku" href="#">決定</a>
                                </div>
                            </aside>
                        </div> -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

実装/西村/確認済み/itemmas/templates/mas_item_register.html
<!-- S03-02 商品情報新規登録

    ToDo
        画面の制作お願いします
        画面の確認
        *長谷川　画像プレビュー出しましたが
        *画像選んでないときにNOIMAGE画像を出したかった　力尽きた

        *views.py、forms.pyの埋め込みタグを記述
        *画面の確認
        *画面のスタイル最終調整
        *最終確認(新満)
-->
{% extends 'base.html' %}
{% load static %}
{% block title %}SIMS | 商品情報新規登録{% endblock %}
{% block main_contents %}
<head>
    <script>
        function imgPreView(event) {
            var file = event.target.files[0];
            var reader = new FileReader();
            var preview = document.getElementById("preview");
            var previewImage = document.getElementById("previewImage");
            // NO IMAGEアイコンを出したかった
            // img.setAttribute("id", "{% static 'assets/img/noimage-icon'%}");
            if(previewImage != null) {
                preview.removeChild(previewImage);
            }
            reader.onload = function(event) {
                var img = document.createElement("img");
                img.setAttribute("src", reader.result);
                img.setAttribute("id", "previewImage");
                preview.appendChild(img);
            };
            reader.readAsDataURL(file);
            }
    </script>
</head>
<body>
    <div class="container-fluid px-4">
        <h1 class="mt-4">商品管理</h1>
        <div class="row">
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table me-1"></i>
                    商品情報新規登録
                </div>
                <!-- image -->
                <div id="preview"></div>
                <!-- <input type="file" accept="image/*" onChange="imgPreView(event)"> -->
                <h2>型番</h2>
                <form method="POST" enctype='multipart/form-data'>
                    {% csrf_token %}
                    {{form.item_image}}
                    
                    <table class="table">
                        {% if form.errors %}
                        <div class="errorlist">
                            {% for errors in form.errors.values %}
                            {% for error in errors %}
                            {{ error }}<br>
                            {% endfor %}
                            {% endfor %}
                        </div>
                        {% endif %}

                        {% for field in form %}
                        <div class="field">
                            {{ field.label_tag }}
                            {{ field }}
                            {% if field.help_text %}
                            <span class="helptext">{{ field.help_text }}</span>
                            {% endif %}
                        </div>
                        {% endfor %}
                    </table>
                    <button class="btn btn-primary" type="submit">登録</button>
                    <button class="btn btn-primary" type="submit"><a href="{% url 'itemmas:S03-05' %}">詳細登録</a></button>
                </form>

                <div class="itemmas-table item-table">                    
                    <table>
                        <thead class="tablecolumn">
                            <tr>
                                <!-- <th>{{label}</th> -->
                                
                            </tr>
                        </thead>
                    </table>
                </div>
                
                    <div class="center-button">
                        <!-- <button class="btn btn-primary" type="submit">登録</button> -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %}

実装/西村/確認済み/itemmas/templates/mas_item_register1.html
<!-- S03-02 商品情報新規登録

    ToDo
        画面の制作お願いします
        画面の確認
        *長谷川　画像プレビュー出しましたが
        *画像選んでないときにNOIMAGE画像を出したかった　力尽きた

        *views.py、forms.pyの埋め込みタグを記述
        *画面の確認
        *画面のスタイル最終調整
        *最終確認(新満)
-->
{% extends 'base.html' %}
{% load static %}
{% block title %}SIMS | 商品情報新規登録{% endblock %}
{% block main_contents %}
<head>
    <script>
        function imgPreView(event) {
            var file = event.target.files[0];
            var reader = new FileReader();
            var preview = document.getElementById("preview");
            var previewImage = document.getElementById("previewImage");
            // NO IMAGEアイコンを出したかった
            // img.setAttribute("id", "{% static 'assets/img/noimage-icon'%}");
            if(previewImage != null) {
                preview.removeChild(previewImage);
            }
            reader.onload = function(event) {
                var img = document.createElement("img");
                img.setAttribute("src", reader.result);
                img.setAttribute("id", "previewImage");
                preview.appendChild(img);
            };
            reader.readAsDataURL(file);
            }
    </script>
</head>
<body>
    <div class="container-fluid px-4">
        <h1 class="mt-4">商品管理</h1>
        <div class="row">
            <div class="card mb-4">
                <!-- <div class="card-header">
                    <i class="fas fa-table me-1"></i>
                    商品情報新規登録
                </div> -->
                <!-- image -->
                <div class="card-body">
                    <div class="itemmas-table spec-table">
                        <table class="listtable sub2">
                            <form method="POST" enctype='multipart/form-data'>
                                {% csrf_token %}
                                {{form.as_p}}
                                <button class="btn btn-primary" type="submit">登録</button>
                                
                            </form>
                            <thead class="tablecolumn">
                                <tr>
                                    <th>メーカー</th>
                                    <td><input type="text" id="" name="" placeholder="メーカー"></td>
                                    <th>モニタサイズ</th>
                                    <td><input type="text" id="" name="" placeholder="モニタサイズ"></td>
                                </tr>
                                <tr>
                                    <th>CPU</th>
                                    <td><input type="text" id="" name="" placeholder="CPU"></td>
                                    <th>モニタ解像度(縦)</th>
                                    <td><input type="text" id="" name="" placeholder="解像度(縦)"></td>
                                </tr>
                                <tr>
                                    <th>HDD</th>
                                    <td><input type="text" id="" name="" placeholder="HDD"></td>
                                    <th>モニタ解像度(横)</th>
                                    <td><input type="text" id="" name="" placeholder="解像度(横)"></td>
                                </tr>
                                <tr>
                                    <th>SSD</th>
                                    <td><input type="text" id="" name="" placeholder="SSD"></td>
                                    <th>カメラ</th>
                                    <td><input type="text" id="" name="" placeholder="カメラ"></td>
                                </tr>
                                <tr>
                                    <th>OS</th>
                                    <td><input type="text" id="" name="" placeholder="OS"></td>
                                    <th>光学ドライブ</th>
                                    <td><input type="text" id="" name="" placeholder="光学ドライブ"></td>
                                </tr>
                                <tr>
                                    <th>Wi-Fi</th>
                                    <td><input type="text" id="" name="" placeholder="Wi-Fi"></td>
                                    <th>グラフィック</th>
                                    <td><input type="text" id="" name="" placeholder="グラフィック"></td>
                                </tr>
                            </thead>
                        </table>
                        <div class="placement-center">
                            <button class="btn btn-primary" type="submit">登録</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %}